### ISSUE TITLE
Missing docs: Parsed data notes for dispersionenergies

### ISSUE THREAD

**Issue by arosen93** [cclib/cclib#1100]
The attribute `dispersionenergies` is missing from the parsed data notes documentation [here](https://cclib.github.io/data_notes.html#dispersionenergies). Just a head's up! 

I also found the description for `scfenergies` to be unclear about whether or not it includes additional corrections, e.g. dispersion.

**Comment by berquist** [comment]
If I remember #664 correctly, the conclusion was that since we expect dispersion to be a part of the final SCF energy when reading an output file, like the nuclear repulsion energy, and that some corrections are included self-consistently (VV10), `scfenergies` (and by extension `mpenergies` and `ccenergies`) includes `dispersionenergies`. I think it's obvious when you read that, but yes, not at all otherwise.

**Comment by arosen93** [comment]
Thanks for commenting here. Yes, that was my conclusion as well when I read #664 a little while back (which I confirmed on my own calculations as well). Definitely made me pause for a few minutes though and question the philosophical meaning of an SCF energy ;)

**Comment by berquist** [comment]
@arosen93 Please check the associated PR and let me know if it's clear enough.

**Comment by arosen93** [comment]
@berquist, thanks for doing this! Yes, it reads very clearly now. No ambiguity!
