### ISSUE TITLE
Wrong description in the manual for moenergies

### ISSUE THREAD

**Issue by KamijouMikoto12311** [cclib/cclib#1478]
I am using cclib 1.8.1, to read the log file generated by gaussian, and the output of moenergies is actually in the unit of eV instead of Hartree, while the manual says it is in the unit of hartree.

**Comment by berquist** [comment]
Apologies for the late response.  The reason for this is because we currently only have one version of the docs and it mostly only follows the `master` branch rather than the last tagged release (here, 1.8.1).  The only section that really covers the last tagged release is "Parsed data (version 1.8.1)", not "Parsed data notes".  The units changed in some commits to `master` after 1.8.1, but these will be reverted in the near future (https://github.com/cclib/cclib/issues/1482), so both the docs and code in 1.8.2 will have these units in eV.

This is something we want to fix properly (https://github.com/cclib/cclib/issues/1439) in the future.``
