### ISSUE TITLE
Chemical JSON support

### ISSUE THREAD

**Issue by langner** [cclib/cclib#156]
Related to #17
Related discussion on avogadr-devel: http://sourceforge.net/p/avogadro/mailman/message/33162153/

**Comment by langner** [comment]
With @berquist's new code it seems this could make it into 1.4 with some effort. That would be really cool.

**Comment by berquist** [comment]
@langner has brought up that we might not want our own XYZ writing code (#174). Whether or not we do, it currently contains functionality for choosing geometries that needs to be abstracted more.

Further work that still needs to be done, for 1.4:
1. Be able to split the output into multiple files if multiple geometries are requested.
2. Abstract the selection of the geometry (for when parsing a file with multiple geometries).
3. Implement a generic interface to Open Babel, where any formats supported by Open Babel are available for export. We don't use this interface for CML unless explicitly asked, because we want to go beyond OpenBabel's CML capabilities.

**Comment by langner** [comment]
CJSON support was added in #169 and we now have `ccwrite` as general output mechanism. I consider this fixed and ready for v1.4 - anything we're still missing before closing this?

**Comment by ATenderholt** [comment]
Have we passed our new proposed attributes by OpenChemistry to see what they think? Especially for the ```energy``` and its sub-attributes. For instance, I think the alpha/beta MO energies would make more sense under an ```orbitals``` attribute (or something similar).

**Comment by berquist** [comment]
I spoke to Marcus at ACS last year and over email; in response to the question "What is the reference implementation of CJSON that I should be looking at with regards to quantum chemical data?", he replied:

> There isn't currently anything beyond some informal discussions, but I am eager to get it fleshed out. We would like to take advantage of the way BSON/JSON store data, so rather than having many small arrays with objects, using larger arrays to store indexed properties. In the style used for coordinates, bond orders, etc.

He also mentioned that they're (he is) very open to suggestions for additions. We can also ask @ghutchis for his opinion, since [PQR](https://pqr.pitt.edu/) is a major user of CJSON now.

As far as the current implementation is concerned, it is based off the top example on the [OpenChemistry](http://wiki.openchemistry.org/Chemical_JSON) page. The "reference" implementation is in [avogadrolibs](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/io/cjsonformat.cpp), which has seen some modifications since this was written. Everything in the [commit history](https://github.com/OpenChemistry/avogadrolibs/commits/master/avogadro/io/cjsonformat.cpp) from 2015 is not present in our writer, such as wavefunction type, MO energies and occupancies, and vibrational modes and frequencies.

At a minimum, checking for attributes needs to be added before attempting to write, per https://github.com/cclib/cclib/issues/261.

**Comment by ghutchis** [comment]
As @berquist indicates, the reference implementation is in avogadrolibs, but I'd suggest pushing most attributes to after 1.4. There clearly needs to be at least a short discussion on syntax and I gather that @langner wants a release soon.

**Comment by ghutchis** [comment]
Open Babel will certainly support many of the attributes proposed in CJSON, but I've had a "wait until there's a clearer syntax" view.

**Comment by langner** [comment]
Yes, I am going to push for releasing v1.4 on April 24th. That'll give a
newer point of reference for updating the docs and room for development
with this and during GSOC more generally.

**Comment by berquist** [comment]
I've added some basic checks for attributes before writing in https://github.com/cclib/cclib/pull/265.

**Comment by langner** [comment]
Thanks @berquist I think that's a good change to include in v1.4. Marking this as 1.5, thought, since we want a broader discussion.

**Comment by berquist** [comment]
For reference, it looks like the [CJSON example repository](https://github.com/OpenChemistry/chemicaljson) will help guide us on future development.

**Comment by langner** [comment]
Anything else to do here?

**Comment by berquist** [comment]
Nope, this is basically done.
