### ISSUE TITLE
CML output

### ISSUE THREAD

**Issue by langner** [cclib/cclib#17]
(Moved from https://sourceforge.net/p/cclib/feature-requests/6/)

Created: 2011-11-03
Creator: Karol M. Langner

It might be nice to be able to save parsed data in CML.

**Comment by langner** [comment]
CML output was added in #169 so this is basically done. I'll keep it open for a few more days in case someone wants to comment before v1.4 is release, similar to #156.

**Comment by berquist** [comment]
At a minimum, checking for attributes needs to be added before attempting to write, per https://github.com/cclib/cclib/issues/261.

**Comment by berquist** [comment]
I've added some basic checks for attributes before writing in https://github.com/cclib/cclib/pull/265.

**Comment by langner** [comment]
Cool. @berquist, do you consider CML support complete at this point?

**Comment by berquist** [comment]
To the best of my knowledge, this is the level that Avogadro v1 supports (see [here](https://github.com/openbabel/openbabel/blob/76420f4d4c6bf786a5a0671f7c9b169718257121/src/formats/xml/cmlformat.cpp)). It may be more well-defined in other libraries/programs, but since Avogadro v1/v2 are the most important in my mind, I'd consider this feature complete.

There may be one or two more problems (I'm looking for differences in Open Babel/cclib output), which I'll have small fixes in for tonight or tomorrow.

**Comment by langner** [comment]
OK then, fixed. We can deal with any issues downstream.
