### ISSUE TITLE
Do you plan to support parse Gaussian Formatted Checkpoint file?

### ISSUE THREAD

**Issue by ruixingw** [cclib/cclib#252]
As the title asked, do you have any plan for a FCHK parser? FCHK sometimes contains more detailed data and better precision..

**Comment by langner** [comment]
Perhaps. This was also an idea a few years ago, and I don't remember why we didn't go ahead with it. Would you be willing to provide us with formatted checkpoint files that correspond to out unit tests?

**Comment by ghutchis** [comment]
I can provide some fchk files. One warning that (at least) Q-Chem and Gaussian fchk files are different. Let me know what unit tests you'd like covered.

**Comment by ghutchis** [comment]
We might also be able to provide some support by adapting things from Open Babel and Avogadro.

**Comment by berquist** [comment]
> One warning that (at least) Q-Chem and Gaussian fchk files are different.

I'm not surprised in the slightest. This reminds me of the Molden file "fixer" I wrote because no program is consistent in generating those either. I should add that here and finish working on my writer...

[For our reference, here is the official documentation for formatted checkpoint files.](http://www.gaussian.com/g_tech/g_ur/f_formchk.htm)

> Let me know what unit tests you'd like covered.

I think a reasonable first stab is generating a *.fchk for each of the test inputs in `data/Gaussian/basicGaussian09` (they should run reasonably fast) and I will do the same for Q-Chem. @langner, does this sound good?

Are there any other programs we support that can generate these?

**Comment by ghutchis** [comment]
#259 gives the initial *.fchk from `data/Gaussian/basicGaussian09`

**Comment by jaimergp** [comment]
> For our reference, here is the official documentation for formatted checkpoint files.

For future reference, the spec is now at [/interfacing](http://gaussian.com/interfacing/).
