### ISSUE TITLE
Support trajectories (time)

### ISSUE THREAD

**Issue by langner** [cclib/cclib#289]
In #283 Ramon added support for BOMD trajectories in Gaussian, and there is a regression test for that coming with cclib/cclib-data#36. It would be great to also add unit tests for some standard MD method that multiple programs have. I don't know if that would be BOMD?

**Comment by berquist** [comment]
Yes, BOMD as opposed to ELMD, CPMD, ADMP, or anything else similar to Car-Parrinello. BOMD is much simpler theoretically, therefore it should have fewer knobs to turn in each program, and there are less likely to be implementation differences between each program.

We can run BOMD calculations for at least Gaussian, NWChem, ORCA, and Q-Chem.

**Comment by langner** [comment]
Do you think you could run the jobs? I can do most of the parser code.

**Comment by berquist** [comment]
Yes, I'll run the NWChem, ORCA, and Q-Chem jobs as duplicates of the Gaussian calculation that's been added to the regression files.

**Comment by langner** [comment]
Maybe something with DVB might fit better into our current unit tests.

**Comment by berquist** [comment]
Oh, it's DVB with B3LYP/STO-3G, so same as the unit tests.

**Comment by langner** [comment]
Ah cool, didn't even notice. Are the starting coordinates the same?

**Comment by berquist** [comment]
Based on looking at the standard orientation and rotational constants, yes.

**Comment by langner** [comment]
Great!

**Comment by berquist** [comment]
Should these go in `regressions` or will they have unit tests?

**Comment by langner** [comment]
I'd put them in as unit tests, since we don't have other tests that cover `time`. However, is it possible to trim down on the size compared to the regression test Ramon added?

**Comment by berquist** [comment]
Yes, I'll lower the print level.

**Comment by langner** [comment]
@berquist did you ever get around to running these?

**Comment by berquist** [comment]
It looks like I have ORCA, Q-Chem, NWChem, and perhaps GAMESS.

**Comment by berquist** [comment]
It's pretty clear that I can have this in and tested almost immediately, but my tests are failing because the number of steps/time points aren't consistent with the number of SCF energies and geometries. Except for Gaussian, there is always 1 more SCF energy than time point, because first the energy is converged and the gradient is calculated to obtain the initial forces. Well, it looks like Gaussian is doing the same thing, but the 1 fewer may come from the rejected step elimination, I can't quickly tell. The other programs do traditional MD.

Some programs might not even print intermediate geometries (NWChem), but I'll look to see if I can turn the print level up.

What should our convention for dimensions be? Should we expect the user to know the program's convention?

**Comment by langner** [comment]
> What should our convention for dimensions be? Should we expect the user to know the program's convention?

I think it's reasonable to assume users understand what the program does in order to use the parsed data. As far as tests are concerned, we can parametrize them for programs that behave different, like we do for [`atomcoords` in GeoOpt tests](https://github.com/cclib/cclib/blob/master/test/data/testGeoOpt.py#L29):

**Comment by berquist** [comment]
I think the only blocker is the XYZ reader, so this shouldn't require much more.

**Comment by berquist** [comment]
This was done in https://github.com/cclib/cclib/pull/576, so now there is Gaussian, NWChem, and Q-Chem. Do we want ORCA? It looks like there was an issue with the trajectory being printed to a separate XYZ file.

**Comment by langner** [comment]
I think we can close this old issue. We'll track ORCA separately when somebody wants it.
