### ISSUE TITLE
cclib imports should be relative

### ISSUE THREAD

**Issue by baoilleach** [cclib/cclib#367]
cclib should use relative imports, and not require its presence on the PYTHONPATH.

For example, filewriter.py contains:
   from cclib.parser.utils import PeriodicTable

I bundle cclib with GaussSum, and so this fails.

**Comment by baoilleach** [comment]
The problem with GaussSum was addressed by moving the cclib codebase up a directory so that "from cclib" now works. However, I do have a feeling that within the library all imports should be relative. It would be good to look up best practices on this as it must be a problem that many Python libraries have faced.

**Comment by berquist** [comment]
> The problem with GaussSum was addressed by moving the cclib codebase up a directory so that "from cclib" now works.

Right, taking advantage of the quick-and-dirty import from the file or folder that's in my current directory, and nothing breaks because there are no relative imports in the library but there are `__init__.py` files in the correct locations.

One case where this is a potential problem is if there are multiple copies of cclib in your PYTHONPATH, it's easier for subtle problems to appear. I might have had problems with this in the past where something is wrong with my virtualenv I develop in, and I pick up the system copy instead since they live in the same module namespace, which shouldn't be possible with the relative imports.

Here is a comment on it from [PEP 8](https://www.python.org/dev/peps/pep-0008/#imports):

> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path ):

>     import mypkg.sibling
>     from mypkg import sibling
>     from mypkg.sibling import example

> However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose:

>     from . import sibling
>     from .sibling import example

> Standard library code should avoid complex package layouts and always use absolute imports.

> Implicit relative imports should never be used and have been removed in Python 3.

where an implicit relative import would be just `import sibling`.

I am not convinced that our absolute imports are too verbose and need to be shortened, but I agree that we need more examples. I decided to go with this package structure for a project of mine, and it can be irritating working inside of it; a loose package script that was previously run as `python test_ecd.py` changes to `python -m pyresponse.test_ecd`, so we can already see how our testing scripts might change.

**Comment by langner** [comment]
Let's deal with this for the next release (1.5.2 or 1.6, whatever comes first).

**Comment by langner** [comment]
Will review for v1.5.3.

**Comment by berquist** [comment]
Right now, everything has been converted to use absolute imports via https://github.com/cclib/cclib/pull/458 except for some relative imports in the test directory. pytest is also working. @baoilleach should tell us if everything is still working from his end.

**Comment by langner** [comment]
Agreed, looks good on my end, and I also support using absolute imports as recommended by PEP9. @baoilleach do let us know if something is not working still.
