### ISSUE TITLE
NPA charges from Gaussian 09 output wrongly parsed

### ISSUE THREAD

**Issue by langner** [cclib/cclib#406]
This is copied over from an issue filed in cclib/cclib.github.io#28 by @stefabat.

Hey there,

I would like to notify a bug regarding the parsing of NPA charges from a gaussian09 log file (d01 version), computed using NBO6, but I believe is the same also with the gaussian builtin NBO3 program.

The bug appears when parsing natural charges for molecules having more than 99 atoms.
When this is the case, there is no more space between the symbol of the atom and the atom number in the output of the natural population analysis, e.g.

...
H 98 ...
H 99 ...
H100 ...
...

And basically, the charges starting at 100 are just nuts.
It suffices however to modify the log file of gaussian and add a space between the atom symbol and the atom number to get the correct values of the charges parsed.

Cheers
stefabat

**Comment by langner** [comment]
We would be happy to fix this if you could donate an example logfile that has this problem.

**Comment by langner** [comment]
I'm going to close this if there is no update before v1.5.2 is released.

**Comment by stefabat** [comment]
Sorry for the very late answer, I completely forgot about it and when you wrote last week I was quite busy at a conference.

I checked again and actually the problem is not from cclib, but is from the NBO6 program when used coupled to Gaussian 09. In fact, by using the NBO3 program included in G09, there is no problem in parsing correctly all NPA charges.

I attach two outputs (in the zip file just below), one using NBO3 and one using NBO6.
[t557_b97d3.zip](https://github.com/cclib/cclib/files/1272907/t557_b97d3.zip)

The file ending with "cc-pvdz.log" uses NBO6 and shows the problem (check lines 5804 - 5884). As you can see, there is no space between the atom type and the atom number, thus leading to the parsing problem.

The file ending with "cc-pvtz.log" uses NBO3 and does not show the problem (check lines 9736 - 9816). There is space between type and number and there is no problem in parsing.

So that's it..

Sorry again for the late answer.
Cheers
