### ISSUE TITLE
Separate psi3 parser into separate legacy code, and trim

### ISSUE THREAD

**Issue by langner** [cclib/cclib#494]
Offshoot from #319

**Comment by berquist** [comment]
I think this is an opportunity for some breaking changes regarding renames, at least of data files. This is because 4 is part of the program name, and part of the version is separate. Here is my proposal:

* Rename `Psi -> Psi4`, with an alias to `Psi`.
* The new parser is named `Psi3`.

For unit tests,
* `Psi/basicPsi4.0 -> Psi4/basicPsi4-1.0`

For regressions,
* `Psi/Psi3 -> Psi3/Psi3.4`
* `Psi/Psi4.0b5 -> Psi4/Psi4-beta5`
* `Psi/Psi4.0 -> Psi4/Psi4-0.5`

Just as an example:
* `Version 3.4 Alpha`
* `PSI 4.0.0-beta5 Driver`
* `Psi4 0.5 Driver`
* `Psi4 1.0.54 Driver`

**Comment by berquist** [comment]
Done in https://github.com/cclib/cclib/pull/501 and https://github.com/cclib/cclib-data/pull/78.
