### ISSUE TITLE
Generate changelog from one canonical version

### ISSUE THREAD

**Issue by langner** [cclib/cclib#618]
Idea from #616, since we now have two copies of the changelog in the repo.

**Comment by Chokerino** [comment]
WOuld it be okay to use docutils or are we looking for a simple script just or this job?

**Comment by langner** [comment]
@Chokerino I'm not sure, in what capacity were you thinking of using docutils?

**Comment by Chokerino** [comment]
@langner docutils has command line functions like rst2html which we can further parse to generate simple text

**Comment by langner** [comment]
I don't have a strong opinion here, as long as it doesn't pull in a lot of dependencies. However, I think it makes sense to go from the CHANGELOG file to the markdown doc, not the other way around,

**Comment by berquist** [comment]
At work we use [`towncrier`](https://pypi.org/project/towncrier/) to generate the changelog at each version bump from fragment files that get added during each PR.

**Comment by Chokerino** [comment]
@langner Ok ill look into that but in #616 @berquist mentioned to do this way(rst to plain text) so can we decide the method?

**Comment by langner** [comment]
It doesn't matter to me which way we go, forwards or backwards :) towncrier looks like a good choice, especially since Eric knows it. And there'll less work at release time, ti seems.

I presume we'll need to do some extra conversion anyway, unless towncrier can export both text and rst (haven't read any of it's docs).

**Comment by berquist** [comment]
In some ways, towncrier solves a problem that doesn't exist. It's a tool that just adds lines to a text file almost verbatim once a release is minted. This problem, if it is one, is solved by updating an existing changelog by hand in each PR or right after a PR with a link to the issue it closes. But remembering to do that might be a pain either way. We use a PR template that has a checkbox list with a single item for when a newsfragment is added.

> I presume we'll need to do some extra conversion anyway, unless towncrier can export both text and rst (haven't read any of it's docs).

It writes RST. If you want plain text, you'll have to use another tool (like a docutils interface, and I think Sphinx can to it too).

Unfortunately the documentation is nonexistent and the code is not great, so I am not against not using it. Here is a minimum working example:
``` diff
diff --git a/cclib/newsfragments/.gitignore b/cclib/newsfragments/.gitignore
new file mode 100644
index 00000000..f935021a
--- /dev/null
+++ b/cclib/newsfragments/.gitignore
@@ -0,0 +1 @@
+!.gitignore
diff --git a/cclib/newsfragments/694.feature b/cclib/newsfragments/694.feature
new file mode 100644
index 00000000..15705c57
--- /dev/null
+++ b/cclib/newsfragments/694.feature
@@ -0,0 +1 @@
+Log an error when a negative excitation energy is encountered.
diff --git a/pyproject.toml b/pyproject.toml
new file mode 100644
index 00000000..00a629e2
--- /dev/null
+++ b/pyproject.toml
@@ -0,0 +1,33 @@
+[tool.towncrier]
+    package = "cclib"
+    package_dir = ""
+    filename = "NEWS.rst"
+    issue_format = "`#{issue} <https://github.com/cclib/cclib/issues/{issue}>`_"
+
+    [[tool.towncrier.section]]
+        path = ""
+
+    [[tool.towncrier.type]]
+        directory = "feature"
+        name = "Features"
+        showcontent = true
+
+    [[tool.towncrier.type]]
+        directory = "bugfix"
+        name = "Bugfixes"
+        showcontent = true
+
+    [[tool.towncrier.type]]
+        directory = "doc"
+        name = "Improved Documentation"
+        showcontent = true
+
+    [[tool.towncrier.type]]
+        directory = "removal"
+        name = "Deprecations and Removals"
+        showcontent = true
+
+    [[tool.towncrier.type]]
+        directory = "misc"
+        name = "Misc"
+        showcontent = false
diff --git a/requirements.txt b/requirements.txt
index 3a6181c3..5210badf 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -9,6 +9,8 @@ https://sourceforge.net/projects/pyquante/files/PyQuante-1.6/PyQuante-1.6.5/PyQu
 
 # For building the documentation
 sphinx
+# For generating the CHANGELOG
+towncrier
 
 # For testing
 pytest>=3.6

```
and then running it:
```
$ towncrier --draft
Loading template...
Finding news fragments...
Rendering news fragments...
Draft only -- nothing has been written.
What is seen below is what would be written.

Cclib 1.6.1 (2019-03-23)
========================


Features
--------

- Log an error when a negative excitation energy is encountered. (`#694 <https://github.com/cclib/cclib/issues/694>`_)
```
Since it appends to an already existing file, we would want to reformat the existing changelog to match.

**Comment by Chokerino** [comment]
Thanks for the example @berquist. I have tested towncrier and it seems to be working well but if we use this we need to divide our existing changelog into 2(features, bug fixes) or more. 
Also, the appending of data seems to be a problem as for me it drafts both the existing data and the new data added into the NEWS.rst file.

 And do you know why it tries to remove news fragments after writing because for me it always shows an error and if i fix it the appending to file problem would be solved?

**Comment by berquist** [comment]
> divide our existing changelog into 2(features, bug fixes) or more.

I don't think we need to, it should just append to whatever is existing already, and the rest of the file can be reformatted at our leisure.

> Also, the appending of data seems to be a problem as for me it drafts both the existing data and the new data added into the NEWS.rst file.

That sounds like the right behavior? I moved `changelog.rst` from `docs/sphinx` to the top level, changed the name of the file in `pyproject.toml`, ran in non-draft mode, and it wrote this:

```
Cclib 1.6.1 (2019-03-29)
========================

Features
--------

- Log an error when a negative excitation energy is encountered. (`#694 <https://github.com/cclib/cclib/issues/694>`_)


.. index::
    single: development; changelog

Changelog
=========

Changes in cclib-1.6.1
----------------------

**Features**

* New attribute nsocoeffs for natural spin orbital coefficients (Shiv Upadhyay)
* New attribute nsooccnos for natural spin orbital occupation numbers (Shiv Upadhyay)
* New methods: alpha and beta electron counts (Jaime Rodríguez-Guerra)
* Support coreelectrons attribute in Molcas (Kunal Sharma)
* Support etoscs for response calculations in Dalton (Peter Reinholdt)
* Support etenergies for TDDFT in GAMESS
* Support etrotats attribute in ORCA
* Support functional name in metadata for Psi4 (Alessandro Genova)
* Updated testing framework (Jaime Rodríguez-Guerra, Maxim Stolyarchuk and others)
* Updated test file version to QChem 5.1

**Bugfixes**

* Fixed parsing GAMESS output for EOM-CC output
* Fixed parsing Gaussian output for G3 jobs
* Fixed parsing ORCA output for certain invalid inputs (Felipe S. S. Schneider)
* Fixed parsing of mocoeffs in ORCA when they are glued together (Felipe S. S. Schneider)
* Fixed parsing of mocoeffs and vibfreqs in Psi4 (Alessandro Genova)
* Fixed parsing of mocoeffs in Molcas for some files (Shiv Upadhyay)
* Fixed parsing of etsecs in Dalton
* Fixed bond atom indices in CJSON output (Alessandro Genova)

Changes in cclib-1.6
--------------------
<snip>
```

If the Sphinx directive `.. index::` can be placed anywhere and still work, then it could just go at the bottom.

> And do you know why it tries to remove news fragments after writing

It's so you aren't accidentally adding the same fragments under multiple versions in the changelog. But at least it stages everything in Git without committing.

**Comment by Chokerino** [comment]
> I don't think we need to, it should just append to whatever is existing already, and the rest of the file can be reformatted at our leisure

Okay thats also fine. For me thogh it is not removing the newsfragments so i think that needs to be done manually. Also, for generating the text fine we can use rst2txt (https://pypi.org/project/rst2txt/). We just need to run a python script after every towncrier use and it will generate a text file for the `NEWS.rst `. And i think towncrier version should be entered manually.

@langner @berquist if this is fine i can proceed to addling a PR.

**Comment by langner** [comment]
I'm not convinced anymore that this is a good idea. The auto-changelog will basically be a git history... how useful is it to copy that? The changelog in its current form is more useful, since it summarizes, omits less significant changes and organizes into sections like bugfixes. IMO it would be nice to keep that convention.

**Comment by Chokerino** [comment]
But aren't we doing just that. We are segregating the changes into sections
i.e features, bugfixes and since we manually have to edit the newsfragments
we control what is being added in the changelings. This implementation just
makes appending new changes easier and since they text file is
auto-generated we don't need to make changes in two places.

**Comment by langner** [comment]
Where are the newsfragments edited?

**Comment by Chokerino** [comment]
They are basically text files for every segment in a subdirectory and so
before PR we just need to manually add the changes.

**Comment by langner** [comment]
You mean we need to remember to add them with PRs? I don't see how that makes things easier, it just spreads the work out in time.

**Comment by Chokerino** [comment]
I think there is a bit of misunderstanding.
In any case we need to manually update the changelogs and currently, we need to change them in two places. Instead of that, we can update the changelogs by adding the updates in the newsfragments files and then run towncrier and another script for generating a text file from the rst.

Yeah, I can agree that this is about the same effort as what is present.

**Comment by langner** [comment]
I don't really see the added value here, just an extra dependency and different source format. Overall, it seem easier to just add a little script that would translate our CHANGELOG into a markdown version for the logs.

**Comment by Chokerino** [comment]
There is an rst package which can do the job but I am unsure if a single script can do it.

**Comment by berquist** [comment]
Done in #1352.
