### ISSUE TITLE
Support for xTB

### ISSUE THREAD

**Issue by schneiderfelipe** [cclib/cclib#789]
Is support for xtb ([docs](https://xtb-docs.readthedocs.io/en/latest/contents.html), [github](https://github.com/grimme-lab/xtb)) planned? (the xtb program is a package developed by the Grimme group in Bonn that relies on the semiempirical quantum mechanical methods GFNn-xTB.)

**Comment by ghutchis** [comment]
I'd be happy to help with some of that, and it's probably worth paging @awvwgk or similar over here. IMHO, we should start with XTB 6.2 and later. I have older files, but the format changed a lot from v5 which was closed-source anyway.

- Decide on the most important properties to parse
- Generate some example files (e.g., optimizations, vibrations, etc.)

The first thing is to generate a minimally-useful parser:
- energies
- atomic coordinates (e.g., geometry optimization)

What else?

**Comment by awvwgk** [comment]
@ghutchis Thanks for the mention.

`xtb` has some more or less standardized outputs, which could be used for this purpose.

run mode | output
-- | --
single point calculation | Molden file, Turbomole gradient file, Cube files
geometry optimization | xyz trajectory
vibrational frequencies | Gaussian 98 output
molecular dynamics | xyz trajectory

Maybe worth mentioning, I worked on a JSON dump in `xtb` some time ago, which should be still available. Most of the information from a single point calculation is serialized there already.

**Comment by ghutchis** [comment]
@shivupa - we just talked and we will put something together within the week

**Comment by schneiderfelipe** [comment]
Any progress on this?

One minor issue I've found regarding writing a parser (related to #808) is that XTB doesn't seem to provide coordinates within the output file. Not sure how to handle that.

**Comment by awvwgk** [comment]
Not from my side, at least.

Anyone working on this might be tempted to parse the standard output of `xtb`, don't do this, because I don't guarantee its stability and it has changed in the past without prior notice. Prefer one of the structured data dumps (JSON, molden, ...) or access `xtb` via a stable API (Fortran, C, Python, QCEngine, ASE, ...). If any information is not available via those access points, we can implement it upstream, of course.

**Comment by berquist** [comment]
If the JSON dump is not available with the ORCA integration, then we will need to parse the text output.

**Comment by ghutchis** [comment]
I generally see output coordinates when optimizing. One catch is that the output format depends on the input format. So if someone optimizes with an XYZ file, you get the optimized geometry in XYZ. If you use MOL/SDF as input, you'll get that optimized file in the output.

It's a bit tricky, since some of the properties end up in separate files (e.g., vibrations) but I think we can at least have something workable.. we have enough bits of parsing code in my group to piece together a start.

As far as "subject to change without warning," I don't think that's too different from other codes. The JSON output might be more useful, but I don't think that many people use it. (And the AFAICT the JSON from `xtb` is different from the Orca `gbw2json`)

**Comment by ghutchis** [comment]
One question for the core developers (@berquist, @shivupa etc) is about xtb-specific data. We'd like to extract essentially everything, but some of these don't match up with other programs (e.g., atom dispersion coefficients). Would it be okay to add a catch-all dictionary like "properties" for program-specific data?

**Comment by shivupa** [comment]
Would it make sense to put these under `metadata`?

**Comment by ghutchis** [comment]
Most of these attributes don't really feel like "metadata"
- atomic polarizabilities (might be a useful item in other programs)
- atomic dispersion coefficients (ditto)
- calculated atomic coordination numbers
- localization properties (e.g., pi, LP, etc.)

Most of these are really program-specific data, but I'd hesitate to call them "metadata," since that seems to be input keywords, timings, grids, etc. (e.g., metadata about how the job was run).

I'm proposing sort of a program-specific dictionary of misc. attributes along the lines of the metadata dictionary.

**Comment by berquist** [comment]
> I'm proposing sort of a program-specific dictionary of misc. attributes along the lines of the metadata dictionary.

Yes, this is what we do with `transprop` until these quantities "graduate" to their own attributes or are better standardized in some way (such as attributes-as-classes for 2.0).  Definitely the atomic polarizabilities and dispersion coefficients are not unique to xtb, so I could see them graduating.  Localization may be similar to whatever we do for NBO (https://github.com/cclib/cclib/issues/1012).  So +1 from me to your suggestion.

**Comment by ghutchis** [comment]
Some of the properties we parse (solution free energies) seem like they'll be of use for other programs too.

How does this sound for non-standardized properties:
- `atomprop` for misc. atomic properties
- `bondprop` for misc. bond properties (e.g. WBO, MBO, ELF, etc.)
- `prop` for other misc. global properties (we'll probably have a few `transprop` things from `stda`

**Comment by berquist** [comment]
Looks good.

Something I missed:

> One catch is that the output format depends on the input format. So if someone optimizes with an XYZ file, you get the optimized geometry in XYZ. If you use MOL/SDF as input, you'll get that optimized file in the output.

In theory we can parse MOL/SDF via pybel, but I'm not sure if it works, so we may want our own reader.  This should be pretty easy if we don't try and map any custom properties or the bond order/connectivity table and just take the coordinate block.  Is there anything else important they contain?

**Comment by ghutchis** [comment]
> In theory we can parse MOL/SDF via pybel, but I'm not sure if it works, so we may want our own reader.

Since `pybel` and `openbabel` are not guaranteed, the current code parses the atom coordinate block. Since it's `xtb` it's fairly normal - like other quantum programs it expects all atoms to exist (i.e., no implicit hydrogens).

That's one aspect we only realized recently, since our workflow has mostly involved `.xyz` input, so I'll work to make that part as robust as possible.
