### ISSUE TITLE
'homos' returns HOMO-1 index instead of HOMO index for Gaussian 16

### ISSUE THREAD

**Issue by JH5225** [cclib/cclib#846]
[bpyNiII_B3LYP_6311Gd.log](https://github.com/cclib/cclib/files/4530396/bpyNiII_B3LYP_6311Gd.log)

I noticed that the 'homos' command returns the HOMO-1 index instead of the HOMO index for Gaussian 16. 

For example, the HOMO of the calculation in the attached log file has index 54. However, executing 

 'parser = cclib.io.ccopen(bpyNiII_B3LYP_6311Gd.log) 
 data = parser.parse() 
 HOMO = data.homos
print(str(HOMO)'

gives 53 as the HOMO index. This example is a spin-restricted calculation, but the same problem occurs for unrestricted calculations: 'homos' returns the HOMO-1 for both the alpha and beta orbitals.

**Comment by shivupa** [comment]
Hi! This is because the indexing in python start at 0. For example, you would want `data.mocoeffs[HOMO,:]` to return the MO coefficients of the HOMO orbital which it does currently. If 54 was stored then this would return the MO coefficients of the LUMO. Let me know if there are any other questions!

**Comment by langner** [comment]
Adding a bit to the docs in #856 to make this clearer
